paths:
  data: ${hydra:runtime.cwd}/data
  output: ${hydra:runtime.cwd}/output

data:
  predictions:
    file_name: alzh_pred_wide.csv # predictions_data.csv
    encoding: utf-8
    separator: ","

  confidence:
    file_name: confidence_degrees.csv
    encoding: utf-8
    separator: ","
  
  feature_vector:
    folder: ConvNeXtSmall_features
  
  validation_acc:
    filename: validation_accuracies.csv
    encoding: utf-8
    separator: ","

settings:
  verbose: true
  combining_technique: MV  # Options: MV, WMV, RK, ERK (Entropy Ranking), HC, SA, TS

classification:
  enabled: true          # Whether to run classification before ensemble
  classifier: ada        # Options: svm, rf, nn, knn, xgb, catboost, dt, or ada
  test_size: 0.2         # Proportion of data to use for testing
  n_runs: 1              # Number of runs with different seeds
  base_seed: 42          # Base random seed for reproducibility