paths:
  data: ${hydra:runtime.cwd}/data
  output: ${hydra:runtime.cwd}/output

data:
  predictions:
    file_name: ConvNeXtSmall_predictions.csv # alzh_pred_wide.csv # predictions_data.csv
    encoding: utf-8
    separator: ","

  confidence:
    file_name: ConvNeXtSmall_confidence_degrees.csv  #confidence_degrees.csv
    encoding: utf-8
    separator: ","
  
  feature_vector:
    folder: ConvNeXtSmall_features
  
  validation_acc:
    filename: ConvNeXtSmall_val_acc.csv
    encoding: utf-8
    separator: ","

settings:
  verbose: false
  combining_technique: [ERK]  # Options: MV, WMV, RK, ERK (Entropy Ranking), HC, SA, TS [MV, WMV, RK, ERK, HC]
  save_individual_results: false

classification:
  enabled: false          # Whether to run classification before ensemble
  classifier: xgb         # Options: rf, nn, knn, xgb | svm, catboost, dt, or ada
  test_size: 0.2         # Proportion of data to use for testing
  n_runs: 1              # Number of runs with different seeds
  base_seed: 42          # Base random seed for reproducibility