paths:
  data: ${hydra:runtime.cwd}/data
  output: ${hydra:runtime.cwd}/output

data:
  predictions:
    file_name: predictions_data.csv
    encoding: utf-8
    separator: ","

  confidence:
    file_name: confidence_degrees.csv
    encoding: utf-8
    separator: ","
  
  feature_vector:
    folder: Featu

settings:
  verbose: false