paths:
  data: ${hydra:runtime.cwd}/data
  output: ${hydra:runtime.cwd}/Results

data:
  dataset: InceptionV3 # InceptionV3_features
  predictions:
    file_name: InceptionV3_predictions.csv # predictions_data.csv
    encoding: utf-8
    separator: ","

  confidence:
    file_name: InceptionV3_confidence_degrees.csv  #confidence_degrees.csv
    encoding: utf-8
    separator: ","
  
  feature_vector:
    folder: InceptionV3_features
  
  validation_acc:
    filename: InceptionV3_val_acc.csv
    encoding: utf-8
    separator: ","

settings:
  verbose: false
  combining_technique: [MV, WMV, RK, ERK, HC]  # Options: MV, WMV, RK, ERK (Entropy Ranking), HC, SA, TS [MV, WMV, RK, ERK, HC]
  save_individual_results: false

classification:
  enabled: true          # Whether to run classification before ensemble
  classifier: xgb        # Options: rf, nn, knn, xgb | svm, catboost, dt, or ada
  test_size: 0.3         # Proportion of data to use for testing
  n_runs: 20             # Number of runs with different seeds
  base_seed: 42          # Base random seed for reproducibility